
const $=id=>document.getElementById(id);
async function api(url,opts={}){const r=await fetch(url,opts);let d={};try{d=await r.json()}catch{};if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d}
async function status(){try{return await api('/api/auth/status')}catch{return {authenticated:false}}}
function setMsg(id,text,kind=''){const e=$(id);e.textContent=text;e.className='msg '+kind}
async function connectionStatus(){const dot=document.querySelector('#loginConnection .connection-dot');const txt=$('loginConnectionText');dot.className='connection-dot checking';txt.textContent='Checking connection…';try{const d=await api('/api/connection_status');dot.className='connection-dot connected';txt.textContent=`${d.provider} • Connected • ${d.latency_ms} ms • ${d.checked_at}`;return true}catch(e){let msg='Database unavailable';try{const r=await fetch('/api/connection_status');const d=await r.json();if(d.error)msg=d.error}catch{}dot.className='connection-dot failed';txt.textContent=msg;return false}}
const KPI_PERCENT = label => label.includes('%');
const KPI_KEYS = ["First Pass Yield %","Hold for Decision % Qty","PPM Defective","Intensity Tagging %","Defect Rate","Reject % Qty","Process Sigma Level (Approx.)","Salvage % Qty","Rework % Qty","Without Intensity %"];
function targetDisplay(label,v){ if(v===null||v===undefined||v==='') return ''; return KPI_PERCENT(label)?(Number(v)*100).toFixed(2):Number(v).toString(); }
function targetNative(label,v){ if(v===null||v===undefined||v==='') return null; const n=Number(v); if(!Number.isFinite(n)) throw new Error('Target values must be numeric'); return KPI_PERCENT(label)?n/100:n; }
async function loadKpiTargets(){try{const d=await api('/api/admin/kpi_targets');$('kpiTargetsBody').innerHTML=d.rows.map(r=>`<tr><td><b>${esc(r.label)}</b></td><td><input class="kt" data-label="${esc(r.label)}" data-field="target" value="${targetDisplay(r.label,r.target)}" style="width:110px"></td><td><input class="kt" data-label="${esc(r.label)}" data-field="warning" value="${targetDisplay(r.label,r.warning)}" style="width:110px"></td><td><input class="kt" data-label="${esc(r.label)}" data-field="critical" value="${targetDisplay(r.label,r.critical)}" style="width:110px"></td><td><select class="kl" data-label="${esc(r.label)}"><option value="higher" ${r.direction==='higher'?'selected':''}>Higher is better</option><option value="lower" ${r.direction==='lower'?'selected':''}>Lower is better</option><option value="neutral" ${r.direction==='neutral'?'selected':''}>Neutral</option></select></td><td><button class="btn primary" onclick="saveKpiTarget('${String(r.label).replace("'","\'")}')">Save</button></td></tr>`).join('')}catch(e){setMsg('targetMsg',e.message,'err')}}
async function saveKpiTarget(label){try{const inputs=[...document.querySelectorAll(`.kt[data-label="${CSS.escape(label)}"]`)]; const get=f=>inputs.find(x=>x.dataset.field===f)?.value||''; const direction=document.querySelector(`.kl[data-label="${CSS.escape(label)}"]`).value; await api('/api/admin/kpi_target',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({label,target:targetNative(label,get('target')),warning:targetNative(label,get('warning')),critical:targetNative(label,get('critical')),direction})});setMsg('targetMsg',`${label} target updated. Dashboard cards will use the new band on next refresh.`,'ok');}catch(e){setMsg('targetMsg',e.message,'err')}}
async function loadMaster(){try{const d=await api('/api/admin/master_data');$('masterBody').innerHTML=d.rows.map(r=>`<tr><td>${esc(r.list_name)}</td><td>${esc(r.value)}</td><td>${r.active?'Active':'Disabled'}</td><td><button class="delete" onclick="toggleMaster(${r.id},${!r.active})">${r.active?'Disable':'Enable'}</button></td></tr>`).join('')}catch(e){setMsg('masterMsg',e.message,'err')}}
async function toggleMaster(id,active){try{await api('/api/admin/master_data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'toggle',id,active,list_name:'x',value:'x'})});loadMaster()}catch(e){alert(e.message)}}
$('masterList').onchange=()=>{ $('customListWrap').classList.toggle('hidden',$('masterList').value!=='__custom__') };
$('masterAddBtn').onclick=async()=>{setMsg('masterMsg','Adding…');try{await api('/api/admin/master_data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'add',list_name:$('masterList').value==='__custom__'?$('customListName').value:$('masterList').value,value:$('masterValue').value})});$('masterValue').value='';setMsg('masterMsg','Value added.','ok');loadMaster()}catch(e){setMsg('masterMsg',e.message,'err')}};
async function loadExplorer(){try{const d=await api('/api/admin/data_explorer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({heat_no:$('exHeat').value,work_center:$('exWC').value,grade:$('exGrade').value,defect:$('exDefect').value,limit:200})});$('explorerBody').innerHTML=d.rows.map(r=>`<tr><td>${r.id}</td><td>${esc(r.insp_lot_date||'')}</td><td>${esc(r.heat_no)}</td><td>${esc(r.work_center)}</td><td>${esc(r.grade)}</td><td>${Number(r.output_weight||0).toFixed(3)}</td><td>${esc(r.main_defect)}</td><td>${esc(r.defect_intensity)}</td><td>${esc(r.quality_decision)}</td><td><button class="delete" onclick="del(${r.id});setTimeout(loadExplorer,300)">Delete</button></td></tr>`).join('')}catch(e){setMsg('exploreMsg',e.message,'err')}}
$('exploreBtn').onclick=loadExplorer;
async function loadAdminLogs(){try{const h=await api('/api/admin/import_history');$('importHistoryBody').innerHTML=h.rows.map(r=>`<tr><td>${esc(r.filename)}</td><td>${r.detected}</td><td>${r.inserted}</td><td>${r.duplicates}</td><td>${r.errors}</td><td>${esc(r.imported_by)}</td><td>${esc(r.imported_at)}</td></tr>`).join('');const a=await api('/api/admin/audit_log');$('auditBody').innerHTML=a.rows.map(r=>`<tr><td>${esc(r.actor)}</td><td>${esc(r.action)}</td><td>${esc(r.entity)}</td><td>${esc(r.details)}</td><td>${esc(r.created_at)}</td></tr>`).join('')}catch(e){console.error(e)}}

async function loadUsers(){try{const d=await api('/api/admin/users');$('usersBody').innerHTML=d.rows.map(r=>`<tr><td>${esc(r.username)}</td><td>${esc(r.display_name)}</td><td>${esc(r.role)}</td><td>${r.active?'Active':'Disabled'}</td><td>${esc(r.created_at||'')}</td><td>${r.username==='admin'?'—':`<button class="delete" onclick="toggleUser(${r.id},${!r.active})">${r.active?'Disable':'Enable'}</button>`}</td></tr>`).join('')}catch(e){setMsg('userMsg',e.message,'err')}}
async function toggleUser(id,active){try{await api('/api/admin/user_toggle',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,active})});loadUsers()}catch(e){alert(e.message)}}
async function loadActivity(){try{const d=await api('/api/activity');const s=d.summary;$('aTotalUsers').textContent=s.total_users.toLocaleString();$('aUniqueIps').textContent=s.unique_ips.toLocaleString();$('aActiveToday').textContent=s.active_today.toLocaleString();$('aOpensToday').textContent=s.opens_today.toLocaleString();$('aOpens7').textContent=s.opens_7d.toLocaleString();$('aExports30').textContent=s.exports_30d.toLocaleString();$('activityUsersBody').innerHTML=d.users.map(r=>`<tr><td>${esc(r.ip_address||'Unknown')}</td><td>${Number(r.opens||0).toLocaleString()}</td><td>${esc(r.last_seen||'—')}</td><td>${esc(r.user_agent||'—')}</td></tr>`).join('');$('recentActivityBody').innerHTML=d.recent.map(r=>`<tr><td>${esc(r.ip_address||'Unknown')}</td><td>${esc(r.username||'Anonymous')}</td><td>${esc(r.event_type||'')}</td><td>${esc(r.tab||'')}</td><td>${esc(r.created_at||'')}</td></tr>`).join('')}catch(e){console.error(e)}}
$('addUserBtn').onclick=async()=>{setMsg('userMsg','Creating…');try{await api('/api/admin/user',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('u_username').value,display_name:$('u_display_name').value,password:$('u_password').value,role:$('u_role').value})});setMsg('userMsg','User created successfully.','ok');$('u_username').value='';$('u_display_name').value='';$('u_password').value='';loadUsers()}catch(e){setMsg('userMsg',e.message,'err')}};
async function boot(){const s=await status();if(s.authenticated)showAdmin();else {showLogin();connectionStatus()}}
function showLogin(){$('loginBox').classList.remove('hidden');$('adminApp').classList.add('hidden');$('logoutBtn').classList.add('hidden')}
function showAdmin(){$('loginBox').classList.add('hidden');$('adminApp').classList.remove('hidden');$('logoutBtn').classList.remove('hidden');loadRecords();loadUsers();loadActivity();loadKpiTargets();loadMaster();loadExplorer();loadAdminLogs();connectionStatus()}
$('loginBtn').onclick=async()=>{setMsg('loginMsg','');try{await api('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('username').value,password:$('password').value})});showAdmin()}catch(e){setMsg('loginMsg',e.message,'err')}};
$('password').addEventListener('keydown',e=>{if(e.key==='Enter')$('loginBtn').click()});
$('connectionBtn').onclick=()=>connectionStatus();
$('logoutBtn').onclick=async()=>{await api('/api/logout',{method:'POST'});location.reload()};
function formData(){return {insp_lot_date:$('f_insp_lot_date').value,heat_no:$('f_heat_no').value,work_center:$('f_work_center').value,grade:$('f_grade').value,output_weight:$('f_output_weight').value,main_defect:$('f_main_defect').value,defect_intensity:$('f_defect_intensity').value,quality_decision:$('f_quality_decision').value,month:$('f_month').value,week:$('f_week').value,quarter:$('f_quarter').value,financial_year:$('f_financial_year').value}}
$('addBtn').onclick=async()=>{setMsg('addMsg','Saving…');try{const d=await api('/api/admin/record',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(formData())});setMsg('addMsg',`Saved successfully. ${d.inserted} record added.`,'ok');document.querySelectorAll('#adminApp input').forEach(e=>{if(e.id.startsWith('f_')&&e.id!=='f_insp_lot_date')e.value=''});$('f_defect_intensity').value='';$('f_quality_decision').value='';loadRecords()}catch(e){setMsg('addMsg',e.message,'err')}};
$('importBtn').onclick=async()=>{const file=$('fileInput').files[0];if(!file){setMsg('importMsg','Please select a file.','err');return}setMsg('importMsg','Uploading and validating…');$('importResult').innerHTML='';try{const fd=new FormData();fd.append('file',file);const d=await api('/api/admin/import',{method:'POST',body:fd});setMsg('importMsg','Import completed.','ok');$('importResult').innerHTML=`<div class="result"><strong>Detected:</strong> ${d.detected.toLocaleString()} &nbsp; | &nbsp; <strong>Inserted:</strong> ${d.inserted.toLocaleString()} &nbsp; | &nbsp; <strong>Duplicates skipped:</strong> ${d.duplicates.toLocaleString()} &nbsp; | &nbsp; <strong>Validation errors:</strong> ${d.errors.length.toLocaleString()}${d.errors.length?'<br><br>'+d.errors.slice(0,15).map(x=>`Row ${x.row}: ${x.error}`).join('<br>'):''}</div>`;loadRecords()}catch(e){setMsg('importMsg',e.message,'err')}};
async function loadDbStatus(){try{const d=await api('/api/admin/database_status');$('dbProvider').textContent=d.provider+ (d.persistent?' • persistent':' • local');$('dbUsage').textContent=`${d.used_mb.toFixed(2)} MB (${d.usage_pct.toFixed(1)}%)`;$('dbLimit').textContent=`${d.limit_mb.toFixed(0)} MB`;$('dbMeter').style.width=Math.min(d.usage_pct,100)+'%';const labels={healthy:'● Healthy',warning:'● Warning',action:'● Action required',critical:'● Critical'};$('dbStatus').textContent=(labels[d.status]||d.status)+` — ${d.records.toLocaleString()} records`;$('dbStatus').className='db-status '+d.status}catch(e){$('dbStatus').textContent='Database status unavailable'}}
async function loadRecords(){try{const d=await api('/api/admin/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({limit:100})});$('totalRecords').textContent=d.total.toLocaleString();loadDbStatus();$('recordsBody').innerHTML=d.rows.map(r=>`<tr><td>${r.id}</td><td>${r.insp_lot_date||''}</td><td>${esc(r.heat_no)}</td><td>${esc(r.work_center)}</td><td>${esc(r.grade)}</td><td>${Number(r.output_weight||0).toFixed(3)}</td><td>${esc(r.main_defect)}</td><td>${esc(r.defect_intensity)}</td><td>${esc(r.quality_decision)}</td><td>${esc(r.month)}</td><td>${esc(r.week)}</td><td>${esc(r.quarter)}</td><td>${esc(r.financial_year)}</td><td><button class="delete" onclick="del(${r.id})">Delete</button></td></tr>`).join('')}catch(e){setMsg('loginMsg',e.message,'err')}}
function esc(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
async function del(id){if(!confirm('Delete record ID '+id+' permanently?'))return;try{await api('/api/admin/delete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});loadRecords()}catch(e){alert(e.message)}}
$('refreshBtn').onclick=()=>{loadRecords();loadDbStatus();loadUsers();loadActivity();loadKpiTargets();loadMaster();loadExplorer();loadAdminLogs()};
$('backupBtn').onclick=()=>{window.location.href='/api/admin/export_csv'};boot();
